file = open('output.txt', 'w')
text=input("Enter text to write to the file: ")
file.write(text)
print("Data successfully written to output.txt.")
file.close()
print("\n")

file = open('output.txt', 'a')
text = input("Enter additional text to append: ")
file.write("\n"+text)
print("Data successfully appended.")
file.close()
print("\n")

file = open('output.txt', 'r')
text = file.read()
print("Final content of output.txt:")
print(text)
file.close()